export const objectPosition = [
  'top',
  'bottom',
  'left',
  'right',
  'center',
  'top left',
  'top right',
  'bottom left',
  'bottom right',
  'center left',
  'center right',
  'center top',
  'center bottom',
  'left top',
  'left bottom',
  'right top',
  'right bottom',
  'center center',
  'inherit',
  'initial',
  'unset',
  'revert',
];

export const objectFit = ['cover', 'contain', 'fill', 'none', 'scale-down'];

export const scale = [
  'scale(0.5)',
  'scale(0.75)',
  'scale(0.95)',
  'scale(1)',
  'scale(1.25)',
  'scale(1.5)',
  'scale(1.75)',
  'scale(2)',
  'scale(2.25)',
  'scale(2.5)',
  'scale(2.75)',
  'scale(3)',
];
